services:
  miBaseDeDatos:
    image: mysql:8.0.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_dds  # Esta variable crea la base de datos db_dds automáticamente
    volumes:
      - db_data:/var/lib/mysql  # Persistencia de datos
      - ./init-db:/docker-entrypoint-initdb.d  # Directorio para scripts de inicialización
      - .certs:/etc/mysql/certs #montar los certificados del servidor
    command: >
      --ssl-ca=/etc/mysql/certs/ca.pem
      --ssl-cert=/etc/mysql/certs/server-cert.pem
      --ssl-key=/etc/mysql/certs/server-key.pem
volumes:
  db_data:
